### ISSUE TITLE
Habitable Worlds 2017 webpage on nexss.info

### ISSUE THREAD

**Issue by andrewrushby** [Knowinnovation/Nexss-#10]
Hi Andy/Julia

After a successful workshop in Laramie a few weeks ago, we now have some links to the various presentations and breakout sessions available in this document: [HabWorlds.docx](https://github.com/Knowinnovation/Nexss-/files/1540681/HabWorlds.docx)

I realize we don't have our own page dedicated to the conference and have been redirecting to the LPI site, so we should set one up now to list these links, as well as any other potential output from the meeting too like white papers. We are expecting/hoping for at least a couple of reports from the attendees and will need a home for these in the future too. In terms of page style, I am more than happy to defer to your excellent judgement but I envision it following the general template of the other two workshops we have listed on the site right now.

Thanks for your help as always!

**Comment by andrewrushby** [comment]
Update: I've just been asked to ensure that everyone who is listed here is okay with their talks being posted on the site. I've asked USRA to send out an email to the participant list soliciting any objections. Could we hold off on going live with this page until folks have had a chance to respond? Say, a week?

**Comment by julia-figs** [comment]
Hi Andrew - I'll create an unpublished page with these documents and will push it live when I have your approval.

**Comment by andrewrushby** [comment]
Sorry it's taken me a while to close this loop! I've not heard back from anyone regarding having the videos online, so let's go ahead and get that page live when you can.

**Comment by julia-figs** [comment]
Hi Andrew - you can find the published page at http://nexss.info/community/workshops/habitable-worlds-2017/habitable-worlds-2017-presentations-and-breakout-sessions

Let me know if there's anything you would like to see changed.
