### ISSUE TITLE
Website updates!

### ISSUE THREAD

**Issue by andrewrushby** [Knowinnovation/Nexss-#11]
Hi all! I've been given a WHOLE LOAD of updates to implement on the site, and would appreciate your help if possible. Many of these require me to produce the content that you can then add to the backend. The following pages need some attention:

 **FAQs**
These need updating to add language about the new teams, and clarify (or, at least de-obfuscate somewhat) the selection process. Would it be easier if I send over some language for this, or can I edit directly?

 **TEAMS**
1. We need to add/move up Vikki Meadows to the co-leads.
2. A new section/page/subpage called 'Past Teams' for those rolling off this year. Natalie would like this page to contain all of our current teams that are not from the NAI; I will clarify which ones these are ASAP. This page will be a list of the old teams in the format of, for example, Eric Ford [title of project] [2015-2018] etc.
3. Change 'Teams' to 'Current Teams' without making a new page. This will only have our 5 NAI teams, and David Brain (as he joined 2 years ago).

 **MEETINGS**
1. Add our Technosignatures Workshop to the dropdown and link to the LPI page. (I will also add a short release to the NEWS section, but I think I have sufficient edit rights to do that now).

**ACTIVITIES**
New page under 'Community' to outline:
- NAS white papers (we could link to arxiv or upload)
- NExSS Timeline (dunno if you have this yet - will upload if not)
- Lab astro white paper (we could link to arxiv or upload)
- Exoplanet biosignatures papers (we could link to arxiv/Astrobiology or upload)
- JWST Early Release Science that Natalie is working on - there is a paper on the arxiv and a Github repo.
- We sent out a 'State of NExSS' newsletter a few months ago that was originally intended for the team members, but I hope to rework it to make it a bit more public facing and add that too if possible.

Not sure of the best way to organise this page (i.e. different sections, or subpages), but happy to defer to your best judgement. 

**GENERAL**

- The newsfeed hasn't updated recently; perhaps it needs a slight boot (literally, or more electronically) from your end. 
-  The banners on the front page could be updated - perhaps to the new Technosignatures logo.
-  I will update our calendar to reflect upcoming events.

Sorry to dump that all on you! Let's work through it together when you're able. I'll probably start with the news story for Technosigs18.

**Comment by andrewrushby** [comment]
I can confirm that the teams slated to remain on the 'Teams' page are:

1. James Graham
2. Daniel Apai
3. Steve Desch
4. Bill Moore
5. Anthony Del Genio
6. David Brain

**Comment by andyburnett** [comment]
@andrewrushby Morning. The requests have been broken into separate items. We will get those knocked off one at a time, but some of them require more info from you. We will put the info requests with each item, just for simplicity.

**Comment by andyburnett** [comment]
@andrewrushby has the team now confirmed who the complete list of team members? We are ready to change the page, whenever the list is confirmed.
