### ISSUE TITLE
Update teams section

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/Nexss-#13]
TEAMS

We need to add/move up Vikki Meadows to the co-leads.
A new section/page/subpage called 'Past Teams' for those rolling off this year. Natalie would like this page to contain all of our current teams that are not from the NAI; I will clarify which ones these are ASAP. This page will be a list of the old teams in the format of, for example, Eric Ford [title of project] [2015-2018] etc.
Change 'Teams' to 'Current Teams' without making a new page. This will only have our 5 NAI teams, and David Brain (as he joined 2 years ago).

**Comment by andyburnett** [comment]
@andrewrushby All sounds fine. If you could attach the details of the teams, once Natalie has confirmed them. we can make the change.

**Comment by andyburnett** [comment]
@andrewrushby What title should we give to Vikki Meadows, e.g. NASA/GISS ?

**Comment by andrewrushby** [comment]
Vikki is VPL/U.Washington I believe.

**Comment by andrewrushby** [comment]
The sentence at the top of the About The Team page should be replaced with:

The NExSS project is overseen by representatives from NASA headquarters, four co-leads, and a steering committee comprised of the PIs of selected teams. See FAQs for detail information about membership.
