### ISSUE TITLE
Update FAQs

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/Nexss-#14]
FAQs
These need updating to add language about the new teams, and clarify (or, at least de-obfuscate somewhat) the selection process. Would it be easier if I send over some language for this, or can I edit directly?

**Comment by andyburnett** [comment]
@andrewrushby Yes, please attach the language here. And, we can definitely give you commit bit status. However, it does require showing you how to use the backend. So, we will need to arrange a suitable time to video conference.

**Comment by andrewrushby** [comment]
This language is still being put through the HQ meat-grinder to ensure it doesn't get us into trouble. Should have something for you soon! I originally drafted 3 sentences, and it's now 3 paragraphs.  :)

**Comment by andyburnett** [comment]
@andrewrushby How is the meat grinding process going?

**Comment by andrewrushby** [comment]
NExSS was launched as a pilot program in 2015 by program officers at NASA HQ. To help lead the endeavor, they identified 18 teams that a) were already selected for funding within various NASA R&A programs and b) had research goals complimentary to those of NExSS. The PI's of these research teams formed the founding Steering Council for NExSS. Given the successes of the pilot program, NExSS teams and Steering Council members were refreshed in 2018 using the results of the 2017 ROSES selections. 

Going forward, NExSS teams and Steering Council membership will be occur via self-nomination from teams with NASA research funding. The NExSS opportunity was called out in the 2018 NASA ROSES call for proposals (see the calls for the Exobiology (C.5), Habitable Worlds (E.2), and the Exoplanet Research (E.3) Program). Other programs may be added to this call before their due dates, in which case the community will be notified via an amendment to the 2018 ROSES call.  In the future (likely beginning with ROSES 2019), teams will be able to self-identify during the proposal submission process to all relevant ROSES elements.

Service on the Steering Committee is a role fulfilled by the PI’s of the NExSS teams.  Service is expected for the period of performance for that team’s program.  This ensures rolling membership on the Steering Committee.  Individuals can remain affiliated with NExSS indefinitely.  Moreover, anyone in the community that wishes to participate in NExSS activities is invited to do so, regardless of whether they have NASA funding or whether they are on the NExSS Steering Council.

**Comment by andrewrushby** [comment]
That is the latest iteration; I say we post it and I will soon hear about it if there is an issue! It's a quicker means of getting HQ's attention if it's public... :)

**Comment by andrewrushby** [comment]
Our final deadline for this is Monday @ 2pm EST; I will have a final version sent to you soon afterwards.

**Comment by andrewrushby** [comment]
I've heard nothing to the contrary, so the language we're going with is:


NExSS was launched as a pilot program in 2015 by program officers at NASA HQ.  Eighteen inaugural teams were identified that a) were already selected for funding within various NASA R&A programs and b) had research goals complimentary to those of NExSS.  The PI of each team serves on a Steering Committee responsible for driving the activities of the network.  Membership on the Steering Committee is for the same period of performance as the funded ROSES proposal. No additional research funds are provided for participation in the network.

 
Given the success of the program, membership was refreshed in 2018 in a similar manner using the results of the 2017 ROSES selections.  Going forward (likely beginning with ROSES 2019), PIs will be able to volunteer to join the NExSS network by responding to a query during the proposal submission process.  A move in this direction was made in the 2018 ROSES announcement whereby the NExSS opportunity was described in section C.5 (Exobiology), E.2 (Habitable Worlds), and E.3 (Exoplanet Research).  New members will be added at a cadence that coincides with the program reviews.

 
NExSS also offers affiliate membership to persons, groups, or organizations whose research interests, goals, and vision are aligned with those of NExSS and would like to actively participate in NExSS-organized activities (e.g. workshops, conferences, virtual seminars, white papers, working groups etc.).  Affiliate members receive NExSS emails and invitations and are expected to engage with the NExSS community.

**Comment by andrewrushby** [comment]
Andy, we've gone for a complete overhaul of the FAQs and want to replace the entire page: [https://docs.google.com/document/d/1kKOAkgdguI4xq7LCt63KLX_kiB8vA83YU3wah-KVJGg/edit?usp=sharing](url)

**Comment by andyburnett** [comment]
I see that there are still comments on the page. Is this the final final final version? Or, is it still being edited?

**Comment by andrewrushby** [comment]
Ignore those comments; we're good to go!
