### ISSUE TITLE
Update meetings

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/Nexss-#15]
Add our Technosignatures Workshop to the dropdown and link to the LPI page. (I will also add a short release to the NEWS section, but I think I have sufficient edit rights to do that now).

**Comment by andyburnett** [comment]
@andrewrushby Can you send the link?

**Comment by andrewrushby** [comment]
Here's the link: https://www.hou.usra.edu/meetings/technosignatures2018/

**Comment by andyburnett** [comment]
@andrewrushby Now live
