### ISSUE TITLE
 The banners on the front page could be updated - perhaps to the new Technosignatures logo.

### ISSUE THREAD

**Issue by andyburnett** [Knowinnovation/Nexss-#17]

**Comment by andyburnett** [comment]
@andrewrushby Sounds good. Please send the banners. However, it would be great if the graphics dept could provide the banners if a few different sizes, just to make it work better on the mobile devices. Hopefully, they have created the different versions already

**Comment by andrewrushby** [comment]
[Here's the technosignatures workshop banner](https://www.hou.usra.edu/meetings/technosignatures2018/banner.png)

**Comment by andrewrushby** [comment]
When you say graphics department though... :-) I was basically the graphics department for this one, and then LPI rendered it.

**Comment by andyburnett** [comment]
@andrewrushby Now live
