### ISSUE TITLE
Rules of the Road

### ISSUE THREAD

**Issue by andrewrushby** [Knowinnovation/Nexss-#19]
Andy, can we make the Rules of the Road (which is currently behind the login) available on the public facing site? We're requiring new teams to read and agree to it, but they can't access it right now. Would it also be possible to do this without changing the URL? (it's already in the linked email welcome).

-Andrew

**Comment by andrewrushby** [comment]
I realize this last request might be an issue, considering it's https://nexss.info/for-members/rulesoftheroad...

**Comment by andyburnett** [comment]
Now live
