### ISSUE TITLE
New NExSS PIs and old ones to be removed

### ISSUE THREAD

**Issue by adelgenio** [Knowinnovation/Nexss-#22]
[New team members 1018.xlsx](https://github.com/Knowinnovation/Nexss-/files/2563370/New.team.members.1018.xlsx)

**Comment by adelgenio** [comment]
Hi Andy,

One more new PI to add to the new team members on the website:

Chris Reinhard: Upside-Down Biospheres and the Remote Detectability of Life on Reducing Planets

Team members: Shawn Domagal-Goldman, Andy Ridgwell, Giada Arney, Kazumi Ozaki

Thanks, Tony

**Comment by adelgenio** [comment]
And one new Co-I to add to an existing PI's team. Please add

Courtney Dressing (dressing@berkeley.edu)
to Jessie Christiansen's team.

Thanks,
Tony

**Comment by andyburnett** [comment]
@adelgenio One question from my colleagues. Almost none of the new team members, and very few of the PIs have accounts on NExSS. This isn't a problem, but we wondered if you were intending to invite them to join the site, and create a profile.

**Comment by andyburnett** [comment]
Ah, that's what we wondered. We will add the new members, and wait to see
what you would like to do.

Cheers
Andy

**Comment by adelgenio** [comment]
Thanks on both of these, Andy!

Tony

Anthony D. Del Genio
NASA Goddard Institute for Space Studies
2880 Broadway
New York, NY 10025
(212)678-5588
Anthony.D.DelGenio@nasa.gov
http://www.giss.nasa.gov/staff/adelgenio.html
________________________________
