### ISSUE TITLE
NExSS website addition request

### ISSUE THREAD

**Issue by adelgenio** [Knowinnovation/Nexss-#24]
Hi Andy,

May I request another website change?

On the home page, please remove the Environments of Terrestrial Planets Under the Young Sun link and picture (on the far right), and please replace it with the NASA Technosignatures Workshop logo that is already on the rotating banner and a link to the new workshop report (attached).

Thanks,
Tony
[Technosignature Report_Final.pdf](https://github.com/Knowinnovation/Nexss-/files/2699330/Technosignature.Report_Final.pdf)

**Comment by andyburnett** [comment]
@adelgenio Now live.

**Comment by adelgenio** [comment]
Thanks, Andy! - Tony

Anthony D. Del Genio
NASA Goddard Institute for Space Studies
2880 Broadway
New York, NY 10025
(212)678-5588
Anthony.D.DelGenio@nasa.gov
http://www.giss.nasa.gov/staff/adelgenio.html
________________________________

**Comment by adelgenio** [comment]
Hi Andy,

I noticed that the figure's aspect ratio is distorted when one views the web page; can that be fixed?

Thanks,
Tony

**Comment by andyburnett** [comment]
Hi Tony, 
Is it actually the aspect ratio you are concerned about, or just the size of the image? We thought it looked rather too large, but we stuck with the original in case it was important for any reason

**Comment by adelgenio** [comment]
Hi Andy,

I was referring to the aspect ratio, it seems to be stretched in the vertical.  But you are right that the figure itself is on the large side, it would be fine with me if you made it ~half as big as it is now on the page.   It would even be better if the figure could be in-line with the paper reference and funding source to the left and the figure on the right, but if that is not possible or easy to do, don't worry about it.

Thanks,
Tony

**Comment by andyburnett** [comment]
Have a look at this layout. We tried a side by side layout, but we had concerns about how this looks on a phone.

**Comment by adelgenio** [comment]
Thanks, Andy, this looks great.  I Like the idea of the funding source at the end after the figure.  There will be more of these to come as I get them from NExSS PIs, let's use this format as our default.

Tony
