### ISSUE TITLE
New NExSS team

### ISSUE THREAD

**Issue by adelgenio** [Knowinnovation/Nexss-#25]
Hi Andy,

We have a new NExSS team.  Can you please add them to the "About the Team" page on the website?  here is the information:

Team: Sellers Exoplanet Environments Collaboration

PI: Avi Mandell

Other team members: William Danchi, Alex Glocer, Alex Pavlov, Sonny Harman, Elisa Quintana, Eric Lopez, Giada Arney, Jeremy Schnittman, Knicole Colon, Marc Kuchner, Michael Way, Nancy Kiang, Prabal Saxena, Ravi Kopparapu, Scott Guzewich, Thomas Fauchez, Vladimir Airapetian, Weijia Kuang, Yuni Lee

Also, please delete Andrew Rushby from the Management team.

I've attached a photo
![avi_mandell](https://user-images.githubusercontent.com/44878541/52241156-f6ae3080-28a0-11e9-87ef-5ab27a977810.jpeg)
 of Avi you can use.

Thanks, Tony

**Comment by andyburnett** [comment]
Now live :)

**Comment by adelgenio** [comment]
Thanks, Andy!  - Tony

Anthony D. Del Genio
NASA Goddard Institute for Space Studies
2880 Broadway
New York, NY 10025
(212)678-5588
Anthony.D.DelGenio@nasa.gov
http://www.giss.nasa.gov/staff/adelgenio.html
________________________________
