### ISSUE TITLE
NExSS calendar

### ISSUE THREAD

**Issue by adelgenio** [Knowinnovation/Nexss-#26]
Hi Andy,

From the website home page, if I go to Community -> Events calendar, I am brought to the NExSS Google calendar page.  On that calendar, when I go to March there is an entry for March 11 (Astro2020 white papers).  But on the NExSS home page, which displays the calendar on the right side of the page, if I scroll to March nothing is listed on March 11.  How do I get that March 11 entry to display on the home page calendar?  I guess this is a prelude to the more general question of how I can add things to the calendar so that they show up on the home page?

Thanks,
Tony

**Comment by andyburnett** [comment]
We have switched to Agenda view, which shows the March meeting, and is probably the more sensible view. 

We have just invited you to become the manager of the calendar. Please let me know if you would like to use a different email address.

**Comment by adelgenio** [comment]
Hi Andy,

It has taken some time, but I finally got another NExSS PI to create a "Recent Research" item to put onto the NExSS home page. It can go right underneath the one you did for Jonathan Fortney's paper.  Here are the details:

Title: Three Plausible Dynamical Histories for Exoplanetary Systems (Rebekah Dawson, PI)

Description: We investigate whether the exoplanets we observe formed where we see them today, or if they formed further away from their stars and migrated inwards. Using simulations, we recreate the observed orbital configurations of specific exoplanetary systems through three different dynamical histories, two of which are consistent with in situ formation. We determine that all three dynamical histories are plausible for these systems, and by extension, for all known exoplanetary systems.

Citation: MacDonald, M. G. & Dawson, R. I. 2018, The Astronomical Journal, 156, 228, https://ui.adsabs.harvard.edu/abs/2018AJ....156..228M

![K223](https://user-images.githubusercontent.com/44878541/66141469-bfc82000-e5d1-11e9-8cbb-47c4b332b705.png)

Figure Caption: The orbital evolution from simulations of the exoplanetary system Kepler-223. The planets in this system have been assumed to have formed farther from their star than we observe them today, migrating inwards through time. We show results from the three different dynamical histories we test in each of the rows of the panels. In the first column, we show the progression of the planets' orbital periods. In the second column, we show an angle which describes the orbital configuration of the system. The confined libration (oscillation) of this angle means the planets have locked into their observed orbital configuration.

Funding source: NASA XRP 80NSSC18K0355

Thanks, Tony

**Comment by andyburnett** [comment]
Now live.

**Comment by adelgenio** [comment]
Thanks, Andy. - Tony

Anthony D. Del Genio
NASA Goddard Institute for Space Studies
2880 Broadway
New York, NY 10025
(212)678-5588
Anthony.D.DelGenio@nasa.gov
http://www.giss.nasa.gov/staff/adelgenio.html
________________________________
