### ISSUE TITLE
Affiliates

### ISSUE THREAD

**Issue by andrewrushby** [Knowinnovation/Nexss-#3]
Hi Andy, Julia...

So, we seem to have the go-ahead to start adding some of our new Affiliate members to the site. I think we'd like them added as other users (i.e. with a profile sporting their name, affiliation and expertise keywords), but also listed on their own page nested under the Affiliates subheading under the 'About' section. In terms of style, I expect something similar to our '[About The Team](https://nexss.info/about/who-we-are)' page, but without the thumbnails (for now at least). 

I've collated the responses we've received from the webform into a spreadsheet here:
[NExSS Affiliate Webform Responses.xlsx](https://github.com/Knowinnovation/Nexss-/files/595603/NExSS.Affiliate.Webform.Responses.xlsx)

Thanks,
Andrew

**Comment by julia-figs** [comment]
Hi Andrew - here is what the page looks like with the newly-registered affiliates. Please let me know if you would like a different format or alternate information to be featured on that page.

https://nexss.info/about/nexss-affiliates

**Comment by andrewrushby** [comment]
Thanks for your quick turnaround on this Julia. It looks pretty good to me, but I'll share it with the rest of the committee and gauge their response ASAP.
