### ISSUE TITLE
More papers for the Proxima Portal

### ISSUE THREAD

**Issue by andrewrushby** [Knowinnovation/Nexss-#6]
Hi Julia/Andy

I've identified a few papers to be added to the Proxima Portal when you get a chance. I've [updated my original template](https://docs.google.com/document/d/1M4Tp2rRu16KOxABYchioXyVMA0egg4mboRI9mZnH-h0/edit?usp=sharing) with the new papers (and also highlighted them for clarity). I also think we should change the Formation and Dynamics header to Formation and Characterization instead. 

Thanks!
Andrew

**Comment by julia-figs** [comment]
Hi Andrew,

Thanks for the highlights! I've added the new papers to the portal, tested all of the links, and changed the highlight color from yellow to green. 

Julia
