### ISSUE TITLE
Swapping to LPI site for HabWorlds

### ISSUE THREAD

**Issue by andrewrushby** [Knowinnovation/Nexss-#8]
Hi again Julia and Andy,

Following our Friday meeting, and with the announcement for HabWorlds going out early this week, Shawn has suggested we redirect to the [official LPI page](https://www.hou.usra.edu/meetings/habitableworlds2017/) and drop our fairly sparse webpage on the workshop to avoid confusion.

Apart from that, no other updates!

Thanks,
Andrew

**Comment by julia-figs** [comment]
Hi Andrew - I'm sorry I missed the call this morning. By the time I looked up from my emails it was half past! I've redirected the link on the Community --> Workshops menu to the official LPI page. I've also redirected the link https://nexss.info/habworlds17 to the official page.
