### ISSUE TITLE
NExSS Feedfilter Issue

### ISSUE THREAD

**Issue by andrewrushby** [Knowinnovation/Nexss-#9]
Hi David, Andy

I've been having a few issues with the feed filter interface recently:

1) I seem to have about a 20% success in selecting articles to include from the exclude list. I can't determine a pattern, but some articles can be selected for inclusion and get struck through, for most others nothing happens.
2) For any articles I choose to exclude, regardless how far down the list they are, only the first entry in the list is selected. 
3) Changes can't be saved in either of these cases.
4) I've noticed that a story about Telstar 401 has been at the top of the 'Around the Web' section on the site for a very long time. It's not clear that the feed is refreshing properly.

I've tried using Chrome on my Windows machine, as well as Firefox on CentOS at work. I have the same issues in both cases.

-Andrew

**Comment by andyburnett** [comment]
Looks like the UI library has a bug. We are in the midst of switching to a different library. Should be fixed soon

**Comment by andyburnett** [comment]
Ready for testing.

**Comment by dsl101** [comment]
Well - probably shouldn't be closed until it's tested :)

@andrewrushby I'm still pondering how best to deploy the new version - currently it's connected to a test database, and I've been running it on there. I'd like to backup the current live database first, then I'll send you a link. I'm hoping to do that before the weekend, but if I run out of time, it will be next Tuesday.

**Comment by dsl101** [comment]
OK - Andy / Andrew, feel free to give it a spin: http://git.hub.ki/hosting/feedfilter2.0

Note that's only the temporary URL - I'll move it to the original one when we're happy all is good.

**Comment by dsl101** [comment]
Right - I've found a few glitches relating to updating the browser view when you save changes. I'm working on it now, and will let you know. If you've noticed anything slightly wrong when saving changes, it should be covered by what I'm fixing...

**Comment by dsl101** [comment]
OK - I think I've got most of the bugs out of Save Changes now. So, please do go ahead and let me know if anything still looks wrong.

**Comment by andrewrushby** [comment]
David,

Thank you for your efforts on this! I've given the new interface a test drive and everything seems to be working well.
